use std::io::Read;

fn main() {
    let mut input = String::new();
    std::io::stdin()
        .read_to_string(&mut input)
        .expect("failed to read bindgen output from stdin");

    let header = "// Auto-generated by scripts/gen-bindings.sh — do not edit manually.\n\n
                  use crate::types::*;";
    print!("{}{}", header, bindgen_transform::transform(&input));
}
