/* automatically generated by rust-bindgen 0.64.0 */

#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum Z3_sort_kind {
    Z3_UNINTERPRETED_SORT = 0,
    Z3_BOOL_SORT = 1,
    Z3_INT_SORT = 2,
    Z3_REAL_SORT = 3,
    Z3_BV_SORT = 4,
    Z3_ARRAY_SORT = 5,
    Z3_DATATYPE_SORT = 6,
    Z3_RELATION_SORT = 7,
    Z3_FINITE_DOMAIN_SORT = 8,
    Z3_FLOATING_POINT_SORT = 9,
    Z3_ROUNDING_MODE_SORT = 10,
    Z3_SEQ_SORT = 11,
    Z3_RE_SORT = 12,
    Z3_CHAR_SORT = 13,
    Z3_UNKNOWN_SORT = 1000,
}
