/* automatically generated by rust-bindgen 0.64.0 */

#[repr(i32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum Z3_goal_prec {
    Z3_GOAL_PRECISE = 0,
    Z3_GOAL_UNDER = 1,
    Z3_GOAL_OVER = 2,
    Z3_GOAL_UNDER_OVER = 3,
}
