/* automatically generated by rust-bindgen 0.64.0 */

#[repr(i32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum Z3_param_kind {
    Z3_PK_UINT = 0,
    Z3_PK_BOOL = 1,
    Z3_PK_DOUBLE = 2,
    Z3_PK_SYMBOL = 3,
    Z3_PK_STRING = 4,
    Z3_PK_OTHER = 5,
    Z3_PK_INVALID = 6,
}
