/* automatically generated by rust-bindgen 0.64.0 */

#[repr(i32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum Z3_parameter_kind {
    Z3_PARAMETER_INT = 0,
    Z3_PARAMETER_DOUBLE = 1,
    Z3_PARAMETER_RATIONAL = 2,
    Z3_PARAMETER_SYMBOL = 3,
    Z3_PARAMETER_SORT = 4,
    Z3_PARAMETER_AST = 5,
    Z3_PARAMETER_FUNC_DECL = 6,
}
