/* automatically generated by rust-bindgen 0.64.0 */

#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum Z3_ast_kind {
    Z3_NUMERAL_AST = 0,
    Z3_APP_AST = 1,
    Z3_VAR_AST = 2,
    Z3_QUANTIFIER_AST = 3,
    Z3_SORT_AST = 4,
    Z3_FUNC_DECL_AST = 5,
    Z3_UNKNOWN_AST = 1000,
}
