/* automatically generated by rust-bindgen 0.64.0 */

#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum Z3_ast_print_mode {
    Z3_PRINT_SMTLIB_FULL = 0,
    Z3_PRINT_LOW_LEVEL = 1,
    Z3_PRINT_SMTLIB2_COMPLIANT = 2,
}
